/*
 *
 *  constants
 *
 */

export default function constants(name) {
    const url = `eztekpay/${name}`;

    return {
        LOAD_DASHBOARD: `${url}/LOAD_DASHBOARD`,
        LOAD_DASHBOARD_SUCCESS: `${url}/LOAD_DASHBOARD_SUCCESS`,
        LOAD_DASHBOARD_ERROR: `${url}/LOAD_DASHBOARD_ERROR`,
        LOAD_DASHBOARD_LOADING: `${url}/LOAD_DASHBOARD_LOADING`,
        CLEAR_DASHBOARD_ERROR: `${url}/CLEAR_DASHBOARD_ERROR`,
        // LOAD_DASHBOARD_RECORDS: `${url}/LOAD_DASHBOARD_RECORDS`,
        // LOAD_DASHBOARD_RECORDS_SUCCESS: `${url}/LOAD_DASHBOARD_RECORDS_SUCCESS`,
        // LOAD_DASHBOARD_RECORDS_ERROR: `${url}/LOAD_DASHBOARD_RECORDS_ERROR`,
        SET_FILTER_OBJ: `${url}/SET_FILTER_OBJ`,
        // SET_DASHBOARD_FILTER_OBJ: `${url}/SET_DASHBOARD_FILTER_OBJ`,
        GET_SUMMARY: `${url}/GET_SUMMARY`,
        GET_SUMMARY_SUCCESS: `${url}/GET_SUMMARY_SUCCESS`,
        GET_SUMMARY_ERROR: `${url}/GET_SUMMARY_ERROR`,
        COLLECTED_REPORT_FOR_DATE: `${url}/COLLECTED_REPORT_FOR_DATE`,
        COLLECTED_REPORT_FOR_DATE_SUCCESS: `${url}/COLLECTED_REPORT_FOR_DATE_SUCCESS`,
        COLLECTED_REPORT_FOR_DATE_ERROR: `${url}/COLLECTED_REPORT_FOR_DATE_ERROR`,
        CLEAR_COLLECTED_REPORT: `${url}/CLEAR_COLLECTED_REPORT`,
        SET_HEADER: `${url}/SET_HEADER`,
        SET_INITIAL_HEADER: `${url}/SET_INITIAL_HEADER`,
        UPDATE_REPORT_DETAILS: `${url}/UPDATE_REPORT_DETAILS`,
        UPDATE_REPORT_DETAILS_SUCCESS: `${url}/UPDATE_REPORT_DETAILS_SUCCESS`,
        UPDATE_REPORT_DETAILS_ERROR: `${url}/UPDATE_REPORT_DETAILS_ERROR`
    }
}