/*
 *
 *  constants
 *
 */

export default function constants(name) {
    const url = `eztekpay/${name}`;

    return {
        LOAD_RECORD: `${url}/LOAD_RECORD`,
        LOAD_RECORD_STARTLOAD: `${url}/LOAD_RECORD_STARTLOAD`,
        LOAD_RECORD_SUCCESS: `${url}/LOAD_RECORD_SUCCESS`,
        LOAD_RECORD_ERROR: `${url}/LOAD_RECORD_ERROR`,
        LOAD_RECORDS: `${url}/LOAD_RECORDS`,
        LOAD_RECORDS_SUCCESS: `${url}/LOAD_RECORDS_SUCCESS`,
        LOAD_RECORDS_ERROR: `${url}/LOAD_RECORDS_ERROR`,
        CREATE_RECORD: `${url}/CREATE_RECORD`,
        CREATE_RECORD_SUCCESS: `${url}/CREATE_RECORD_SUCCESS`,
        CREATE_RECORD_ERROR: `${url}/CREATE_RECORD_ERROR`,
        UPDATE_RECORD: `${url}/UPDATE_RECORD`,
        UPDATE_RECORD_SUCCESS: `${url}/UPDATE_RECORD_SUCCESS`,
        UPDATE_RECORD_ERROR: `${url}/UPDATE_RECORD_ERROR`,
        DELETE_RECORD: `${url}/DELETE_RECORD`,
        DELETE_RECORD_SUCCESS: `${url}/DELETE_RECORD_SUCCESS`,
        DELETE_RECORD_ERROR: `${url}/DELETE_RECORD_ERROR`,
        LOAD_RECORDS_WITH_INPUT: `${url}/LOAD_RECORDS_WITH_INPUT`,
        LOAD_RECORDS_WITH_INPUT_SUCCESS: `${url}/LOAD_RECORDS_SUCCESS_WITH_INPUT`,
        LOAD_RECORDS_WITH_INPUT_ERROR: `${url}/LOAD_RECORDS_ERROR_WITH_INPUT`,

        SET_DEFAULT_HEADERS_DATA: `${url}/SET_DEFAULT_HEADERS_DATA`,
        SET_HEADERS_DATA: `${url}/SET_HEADERS_DATA`,
        LOAD_RECORDS_META_DATA: `${url}/LOAD_RECORDS_META_DATA`,
        LOAD_RECORDS_META_DATA_SUCCESS: `${url}/LOAD_RECORDS_META_DATA_SUCCESS`,
        LOAD_RECORDS_META_DATA_ERROR: `${url}/LOAD_RECORDS_META_DATA_ERROR`,
        CLEAR_RECORD: `${url}/CLEAR_RECORD`,
        CUSTOM_MESSAGE: `${url}/CUSTOM_MESSAGE`,
        CLEAR_CUSTOM_MESSAGE: `${url}/CLEAR_CUSTOM_MESSAGE`,
        CLEAR_NOTIFICATIONS: `${url}/CLEAR_NOTIFICATIONS`,
        CLEAR_INITIAL: `${url}/CLEAR_INITIAL`,
        SET_INITIAL: `${url}/SET_INITIAL`,
        CLEAR_ERRORS: `${url}/CLEAR_ERRORS`,
        SET_FILTER_OBJ: `${url}/SET_FILTER_OBJ`,
        SET_DASHBOARD_FILTER_OBJ: `${url}/SET_DASHBOARD_FILTER_OBJ`,
        EDIT_RECORDS_META_DATA: `${url}/EDIT_RECORDS_META_DATA`,
        EDIT_RECORDS_META_DATA_SUCCESS: `${url}/EDIT_RECORDS_META_DATA_SUCCESS`,
        EDIT_RECORDS_META_DATA_ERROR: `${url}/EDIT_RECORDS_META_DATA_ERROR`,

        LOAD_ACTION: `${url}/LOAD_ACTION`,
        LOAD_ACTION_SUCCESS: `${url}/LOAD_ACTION_SUCCESS`,
        LOAD_ACTION_ERROR: `${url}/LOAD_ACTION_ERROR`,
    }
}