export const DEFAULT_LOGIN_ERROR = 'There was an error logging in. Check your credentials and try again. Contact the administrator if the error persists.';
export const DEFAULT_SIGN_UP_ERROR = 'There was an error on signup.  Contact the administrator if the error persists.'
export const DEFAULT_SESSION_TOKEN_ERROR = 'Your session has expired. Please log in again.';
export const DEFAULT_UNEXPECTED_SESSION_ERROR = 'An unexpected error has occured. Please log in again.';
export const WRONG_CREDENTIALS = 'Your credentials were not accepted. Check your email and password and try again.';
export const NOT_AUTHORIZED = 'You are not authorized to access this platform. Please contact our support for help.';
export const ACCOUNT_EXPIRED = 'Your account expired, please contact EzTekPAY team to extend your licence.';
export const EXPIRED_TOKEN = 'Your reset token is not valid.';
export const NO_SUCH_USER = 'No user with this email exists.';
export const DEFAULT_RESET_PASSWORD_ERROR = 'Failed to Reset Password';
export const DEFAULT_FORGOT_PASSWORD_ERROR = 'Failed to Send Password Reset Email';
export const DEFAULT_CHANGE_PASSWORD_ERROR = 'Failed to Change Password';
export const DEFAULT_SESSION_TIMEOUT_ERROR = 'Failed to update Session Timeout';
export const DEFAULT_SESSION_CLEAR_TIMEOUT_ERROR = 'Failed to clear Session Timeout';
export const DEFAULT_VERIFY_OTP_ERROR = 'Failed to verify the code';
export const DEFAULT_RESEND_OTP_ERROR = 'Failed to resend the code';
export const DEFAULT_LOAD_VERSION_ERROR = 'Failed to Load App Version';
export const DEFAULT_UPDATE_VERSION_ERROR = 'Failed to Update App Version';